# Generated by Django 3.1.2 on 2020-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('lifehacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifehack',
            name='category',
            field=models.ManyToManyField(related_name='lifehack', to='categories.LifehackType'),
        ),
    ]
