# Generated by Django 3.1.2 on 2020-10-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifehacks', '0002_lifehack_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifehack',
            old_name='title',
            new_name='name',
        ),
    ]
